export type Suggestion = {
  darija: string
  translit?: string
  meanings: { en: string; fr: string; es?: string; de?: string; it?: string }
}

export const SUGGESTED_POOL: Suggestion[] = [
  { darija: 'salam', translit: 'salam', meanings: { en: 'Hello', fr: 'Salut', es: 'Hola', de: 'Hallo', it: 'Ciao' } },
  { darija: 'labas', translit: 'labas', meanings: { en: "How are you / I'm fine", fr: "Ça va / Je vais bien", es: '¿Qué tal? / Estoy bien', de: "Wie geht's? / Mir geht's gut", it: 'Come stai? / Sto bene' } },
  { darija: 'shukran', translit: 'shukran', meanings: { en: 'Thank you', fr: 'Merci', es: 'Gracias', de: 'Danke', it: 'Grazie' } },
  { darija: 'afak', translit: 'afak', meanings: { en: 'Please / Excuse me', fr: "S'il vous plaît / Excusez-moi", es: 'Por favor / Disculpe', de: 'Bitte / Entschuldigung', it: 'Per favore / Scusi' } },
  { darija: 'bslama', translit: 'bslama', meanings: { en: 'Goodbye', fr: 'Au revoir', es: 'Adiós', de: 'Auf Wiedersehen', it: 'Arrivederci' } },
  { darija: 'mzyan', translit: 'mzian', meanings: { en: 'Good / Fine', fr: 'Bien', es: 'Bien', de: 'Gut', it: 'Bene' } },
  { darija: 'khouya', translit: 'khouya', meanings: { en: 'Brother / bro', fr: 'Frère / mon frère', es: 'Hermano', de: 'Bruder', it: 'Fratello' } },
  { darija: 'khti', translit: 'khti', meanings: { en: 'Sister / sis', fr: 'Soeur / ma sœur', es: 'Hermana', de: 'Schwester', it: 'Sorella' } },
  { darija: 'inshallah', translit: 'inshallah', meanings: { en: 'God willing', fr: 'Si Dieu le veut', es: 'Si Dios quiere', de: 'So Gott will', it: 'Se Dio vuole' } },
  { darija: 'yallah', translit: 'yallah', meanings: { en: "Let's go / come on", fr: 'Allez / On y va', es: 'Vamos', de: 'Los gehts', it: 'Andiamo' } },
  { darija: 'bzaf', translit: 'bzaf', meanings: { en: 'A lot / very', fr: 'Beaucoup / très', es: 'Mucho / muy', de: 'Viel / sehr', it: 'Molto' } },
  { darija: 'smah lia', translit: 'smah lia', meanings: { en: 'Sorry / pardon me', fr: 'Pardon / Désolé', es: 'Perdón / Lo siento', de: 'Entschuldigung / Sorry', it: 'Scusa / Mi dispiace' } },
  { darija: 'wach', translit: 'wach', meanings: { en: 'Question marker (is/are/do?)', fr: 'Marqueur de question (est/êtes/faites?)', es: 'Marcador de pregunta', de: 'Fragewort', it: 'Indicatore di domanda' } },
  { darija: 'fin', translit: 'fin', meanings: { en: 'Where', fr: 'Où', es: 'Dónde', de: 'Wo', it: 'Dove' } },
  { darija: 'daba', translit: 'daba', meanings: { en: 'Now', fr: 'Maintenant', es: 'Ahora', de: 'Jetzt', it: 'Adesso' } },
  { darija: 'ghadi', translit: 'ghadi', meanings: { en: 'Going to / will', fr: 'Va / ira', es: 'Va a / irá', de: 'Wird', it: 'Andrà' } },
  { darija: 'bghit', translit: 'bghit', meanings: { en: 'I want', fr: "Je veux", es: 'Quiero', de: 'Ich will', it: 'Voglio' } },
  { darija: 'ma bghit sh', translit: 'ma bghitsh', meanings: { en: "I don't want", fr: "Je ne veux pas", es: 'No quiero', de: 'Ich will nicht', it: 'Non voglio' } },
  { darija: "ma'andich", translit: 'maandich', meanings: { en: "I don't have", fr: "Je n'ai pas", es: 'No tengo', de: 'Ich habe nicht', it: "Non ho" } },
  { darija: 'mashi', translit: 'mashi', meanings: { en: 'Not / isn’t', fr: 'Pas / n’est pas', es: 'No / no es', de: 'Nicht', it: 'Non' } },
  { darija: 'hna', translit: 'hna', meanings: { en: 'Here', fr: 'Ici', es: 'Aquí', de: 'Hier', it: 'Qui' } },
  { darija: 'ana', translit: 'ana', meanings: { en: 'I / me', fr: 'Je / moi', es: 'Yo / mí', de: 'Ich / mich', it: 'Io / me' } },
  { darija: 'nta', translit: 'nta', meanings: { en: 'You (m)', fr: 'Toi (m)', es: 'Tú (m)', de: 'Du (m)', it: 'Tu (m)' } },
  { darija: 'nti', translit: 'nti', meanings: { en: 'You (f)', fr: 'Toi (f)', es: 'Tú (f)', de: 'Du (f)', it: 'Tu (f)' } },
  { darija: 'huwa', translit: 'huwa', meanings: { en: 'He', fr: 'Il', es: 'Él', de: 'Er', it: 'Lui' } },
  { darija: 'hiya', translit: 'hiya', meanings: { en: 'She', fr: 'Elle', es: 'Ella', de: 'Sie', it: 'Lei' } },
  { darija: 'smiya', translit: 'smiya', meanings: { en: 'Name', fr: 'Nom', es: 'Nombre', de: 'Name', it: 'Nome' } },
  { darija: 'kulshi', translit: 'kulshi', meanings: { en: 'Everything', fr: 'Tout', es: 'Todo', de: 'Alles', it: 'Tutto' } },
  { darija: 'wld', translit: 'wld', meanings: { en: 'Boy / son', fr: 'Garçon / fils', es: 'Niño / hijo', de: 'Junge / Sohn', it: 'Ragazzo / figlio' } },
  { darija: 'bnt', translit: 'bnt', meanings: { en: 'Girl / daughter', fr: 'Fille / fille', es: 'Niña / hija', de: 'Mädchen / Tochter', it: 'Ragazza / figlia' } },
  { darija: 'lkhobz', translit: 'lkhobz', meanings: { en: 'Bread', fr: 'Pain', es: 'Pan', de: 'Brot', it: 'Pane' } },
  { darija: 'atay', translit: 'atay', meanings: { en: 'Tea', fr: 'Thé', es: 'Té', de: 'Tee', it: 'Tè' } },
  { darija: 'zwin', translit: 'zwin', meanings: { en: 'Beautiful / nice', fr: 'Beau / joli', es: 'Bonito', de: 'Schön', it: 'Bello' } },
  { darija: 'skhoun', translit: 'skhoun', meanings: { en: 'Hot', fr: 'Chaud', es: 'Caliente', de: 'Heiß', it: 'Caldo' } },
  { darija: 'bared', translit: 'bared', meanings: { en: 'Cold', fr: 'Froid', es: 'Frío', de: 'Kalt', it: 'Freddo' } },
  { darija: 'kifash', translit: 'kifash', meanings: { en: 'How', fr: 'Comment', es: 'Cómo', de: 'Wie', it: 'Come' } },
  { darija: 'shno', translit: 'shno', meanings: { en: 'What', fr: 'Quoi / Que', es: 'Qué', de: 'Was', it: 'Cosa' } },
  { darija: 'shhal', translit: 'shhal', meanings: { en: 'How much / how many', fr: 'Combien', es: 'Cuánto', de: 'Wie viel', it: 'Quanto' } },
  { darija: 'mashi mushkil', translit: 'mashi mushkil', meanings: { en: "No problem", fr: 'Pas de problème', es: 'No hay problema', de: 'Kein Problem', it: 'Nessun problema' } },
  { darija: 'safi', translit: 'safi', meanings: { en: "Enough / OK / done", fr: 'Assez / OK / terminé', es: 'Suficiente / OK', de: 'Genug / OK', it: 'Basta / OK' } },
  { darija: '3afak', translit: 'afak', meanings: { en: 'Please', fr: 'S’il vous plaît', es: 'Por favor', de: 'Bitte', it: 'Per favore' } },
  { darija: '3la rasi', translit: '3la rasi', meanings: { en: 'You’re welcome (lit. on my head)', fr: 'De rien', es: 'De nada', de: 'Gern geschehen', it: 'Prego' } },
  { darija: 'mabrouk', translit: 'mabrouk', meanings: { en: 'Congratulations', fr: 'Félicitations', es: 'Felicidades', de: 'Glückwunsch', it: 'Congratulazioni' } },
  { darija: 'hmdllah', translit: 'hamdullah', meanings: { en: 'Thanks be to God / I’m fine', fr: 'Grâce à Dieu / Je vais bien', es: 'Gracias a Dios', de: 'Gott sei Dank', it: 'Grazie a Dio' } },
  { darija: 'msemmi', translit: 'msemmi', meanings: { en: 'I am called / my name is', fr: "Je m'appelle", es: 'Me llamo', de: 'Ich heiße', it: 'Mi chiamo' } },
  { darija: 'qahwa', translit: 'qahwa', meanings: { en: 'Coffee', fr: 'Café', es: 'Café', de: 'Kaffee', it: 'Caffè' } },
  { darija: 'sbaH lkhir', translit: 'sabah el kheir', meanings: { en: 'Good morning', fr: 'Bonjour', es: 'Buenos días', de: 'Guten Morgen', it: 'Buongiorno' } },
  { darija: 'mssa lkhir', translit: 'msa el kheir', meanings: { en: 'Good evening', fr: 'Bonsoir', es: 'Buenas noches', de: 'Guten Abend', it: 'Buona sera' } },
  { darija: '3tini', translit: 'atini', meanings: { en: 'Give me', fr: 'Donne-moi', es: 'Dame', de: 'Gib mir', it: 'Dammi' } },
  { darija: 'kbir', translit: 'kbir', meanings: { en: 'Big', fr: 'Grand', es: 'Grande', de: 'Groß', it: 'Grande' } },
  { darija: 'sghir', translit: 'sghir', meanings: { en: 'Small', fr: 'Petit', es: 'Pequeño', de: 'Klein', it: 'Piccolo' } },
  { darija: 'salam 3likom', translit: 'salam 3likom', meanings: { en: 'Peace be upon you (greeting)', fr: 'Paix sur vous (salutation)', es: 'La paz sea contigo', de: 'Friede sei mit dir', it: 'La pace sia con te' } },
  { darija: 'walakin', translit: 'walakin', meanings: { en: 'But / however', fr: 'Mais / cependant', es: 'Pero', de: 'Aber', it: 'Ma / tuttavia' } },
  { darija: 'sahbi', translit: 'sahbi', meanings: { en: 'My friend (m)', fr: 'Mon ami', es: 'Mi amigo', de: 'Mein Freund', it: 'Il mio amico' } },
  { darija: 'sahbti', translit: 'sahbti', meanings: { en: 'My friend (f)', fr: 'Mon amie', es: 'Mi amiga', de: 'Meine Freundin', it: 'La mia amica' } },
  { darija: '3ndek', translit: 'andek', meanings: { en: 'You have', fr: 'Tu as', es: 'Tienes', de: 'Du hast', it: 'Hai' } },
  { darija: '3ndi', translit: 'andi', meanings: { en: 'I have', fr: 'J’ai', es: 'Tengo', de: 'Ich habe', it: 'Ho' } },
  { darija: 'bzzef', translit: 'bzzef', meanings: { en: 'A lot', fr: 'Beaucoup', es: 'Mucho', de: 'Viel', it: 'Molto' } },
  { darija: 'tlfoun', translit: 'telephone', meanings: { en: 'Phone', fr: 'Téléphone', es: 'Teléfono', de: 'Telefon', it: 'Telefono' } },
  { darija: 'dar', translit: 'dar', meanings: { en: 'House', fr: 'Maison', es: 'Casa', de: 'Haus', it: 'Casa' } },
  { darija: 'mskin', translit: 'mskin', meanings: { en: 'Poor person / unlucky', fr: 'Pauvre / malchanceux', es: 'Pobre / desafortunado', de: 'Armer / unglücklich', it: 'Povero / sfortunato' } },
  { darija: 'mzyan bzaf', translit: 'mzyan bzaf', meanings: { en: 'Very good', fr: 'Très bien', es: 'Muy bien', de: 'Sehr gut', it: 'Molto bene' } },
  { darija: '3la slamtk', translit: '3la slamtek', meanings: { en: 'Get well soon / Bless you', fr: 'Prompt rétablissement / À tes souhaits', es: 'Recupérate pronto', de: 'Gute Besserung', it: 'Guarisci presto' } },
  { darija: 'bssa7a', translit: 'bssa7a', meanings: { en: 'Cheers / to your health', fr: 'À ta santé', es: 'Salud', de: 'Prost', it: 'Salute' } },
  { darija: 'tbarakallah', translit: 'tbarakallah', meanings: { en: 'Blessings / well done', fr: 'Bénédictions / bravo', es: 'Bendiciones', de: 'Gesegnet', it: 'Benedizioni' } },
  { darija: 'ma-fhamtsh', translit: 'ma fhemtsh', meanings: { en: "I don't understand", fr: "Je ne comprends pas", es: 'No entiendo', de: 'Ich verstehe nicht', it: 'Non capisco' } },
  { darija: '3awd', translit: 'awd', meanings: { en: 'Repeat / again', fr: 'Répète / encore', es: 'Repite / otra vez', de: 'Wiederholen', it: 'Ripeti' } },
  { darija: 'shwiya', translit: 'shwiya', meanings: { en: 'A little / slowly', fr: 'Un peu / doucement', es: 'Un poco', de: 'Ein bisschen / langsam', it: 'Un po’' } },
  { darija: 'rani jay', translit: 'rani jay', meanings: { en: 'I am coming', fr: 'J’arrive', es: 'Voy', de: 'Ich komme', it: 'Sto arrivando' } },
  { darija: 'safi rah', translit: 'safi rah', meanings: { en: 'That’s it / done', fr: 'C’est tout / fini', es: 'Ya está / hecho', de: 'Das ist alles', it: 'Questo è tutto' } },
  { darija: 'khdam', translit: 'khdam', meanings: { en: 'Work / working', fr: 'Travail / en train de travailler', es: 'Trabajo / trabajando', de: 'Arbeit / arbeitet', it: 'Lavoro / lavorando' } },
  { darija: 'mrid', translit: 'mrid', meanings: { en: 'Sick', fr: 'Malade', es: 'Enfermo', de: 'Krank', it: 'Malato' } },
  { darija: 'msafrin', translit: 'msafrin', meanings: { en: 'Traveling', fr: 'Voyage', es: 'Viajando', de: 'Reisen', it: 'Viaggio' } },
  { darija: 'hadi', translit: 'hadi', meanings: { en: 'This (f)', fr: 'Celle-ci', es: 'Esta', de: 'Diese', it: 'Questa' } },
  { darija: 'hadak', translit: 'hadak', meanings: { en: 'That (m)', fr: 'Celui-là', es: 'Aquel', de: 'Jener', it: 'Quello' } },
  { darija: 'sahha', translit: 'sahha', meanings: { en: 'Health (as a toast)', fr: 'Santé', es: 'Salud', de: 'Gesundheit', it: 'Salute' } },
  { darija: '3ndek chi', translit: 'andek chi', meanings: { en: 'Do you have something?', fr: 'As-tu quelque chose?', es: '¿Tienes algo?', de: 'Hast du etwas?', it: 'Hai qualcosa?' } },
  { darija: 'shuf', translit: 'shuf', meanings: { en: 'Look / see', fr: 'Regarde', es: 'Mira', de: 'Schau', it: 'Guarda' } },
  { darija: 'mskina', translit: 'mskina', meanings: { en: 'Poor woman / pity', fr: 'Pauvre femme', es: 'Pobre mujer', de: 'Arme Frau', it: 'Povera donna' } },
  { darija: 'hmd', translit: 'hmd', meanings: { en: 'Thanks/ praise (short)', fr: 'Merci (court)', es: 'Gracias (corto)', de: 'Danke (kurz)', it: 'Grazie (breve)' } },
  { darija: 'salamti', translit: 'salamti', meanings: { en: 'Your greeting', fr: 'Ta salutation', es: 'Tu saludo', de: 'Dein Gruß', it: 'Il tuo saluto' } },
  { darija: 'bshwiya', translit: 'bshwiya', meanings: { en: 'Slowly / gently', fr: 'Doucement', es: 'Despacio', de: 'Langsam', it: 'Lentamente' } },
  { darija: 'rani m3ak', translit: 'rani m3ak', meanings: { en: 'I am with you', fr: 'Je suis avec toi', es: 'Estoy contigo', de: 'Ich bin bei dir', it: 'Sono con te' } },
  { darija: 'nti zwin(a)', translit: 'nti zwin', meanings: { en: 'You are beautiful', fr: 'Tu es belle', es: 'Eres hermosa', de: 'Du bist schön', it: 'Sei bella' } },
  { darija: 'tkllm', translit: 'tkllm', meanings: { en: 'Speak', fr: 'Parler', es: 'Hablar', de: 'Sprechen', it: 'Parlare' } },
  { darija: 'sowal', translit: 'sowal', meanings: { en: 'Question', fr: 'Question', es: 'Pregunta', de: 'Frage', it: 'Domanda' } },
]

export const SUPPORTED_LANGS = ['en', 'fr', 'es', 'de', 'it'] as const
